#!/usr/bin/env bash
# script that configures a new Ubuntu machine
cmd="echo \"Ceci n'est pas une page\" > /var/www/html/404.html"
sudo apt -y update
sudo apt -y install nginx
sudo sh -c "${cmd}"
sudo sed -i '/listen 80 default_server;/ a \\terror_page 404 /404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
