#!/usr/bin/env bash
# This script is displaying file content in stpry form
while read -r line; do
	USERNAME=$(echo "$line" | cut -d ":" -f 1)
	GROUPID=$(echo "$line" | cut -d ":" -f 4)
	HOME_DIRECTORY=$(echo "$line" | cut -d ":" -f 6)
	SHEL=$(echo "$line" | cut -d ":" -f 7)
	USER_ID=$(echo "$line" | cut -d ":" -f 3)
	PASSWORD=$(echo "$line" | cut -d ":" -f 2)
	USERINFO=$(echo "$line" | cut -d ":" -f 5)
	echo "The user $USERNAME is part of the $GROUPID gang, lives in $HOME_DIRECTORY and rides $SHEL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USERINFO"
done </etc/passwd
